const fs = require('fs');

const weaponsFile = fs.readFileSync('./src/game/data/weapons.ts', 'utf-8');
const weaponsMatch = weaponsFile.match(/export const WEAPONS: Record<WeaponType, WeaponConfig> = ({[\s\S]+});/);

if (!weaponsMatch) {
    process.exit(1);
}

const keys = [];
const regex = /"([^"]+)": {/g;
let match;
while ((match = regex.exec(weaponsMatch[1])) !== null) {
    keys.push(match[1]);
}

const weaponDir = './public/weapons';
const files = fs.readdirSync(weaponDir);

const FALLBACK_MAP = {
    'multi_bazooka': 'bazooka',
    'hunting_rifle': 'laser_rifle',
    'sniper_rifle': 'laser_rifle',
    'shotgun': 'peacemaker',
    'bozar': 'avenger',
    'rad_rifle': 'avenger',
    'bozar16': 'avenger',
    'bozar24s': 'avenger',
    'laser_pistol2': 'laser_pistol',
    'gauss_pistol2': 'gauss_pistol',
    'beretta': 'handgun',
    'pistol': 'handgun',
    'laser_at_rifle': 'laser_rifle',
    'plasma_at_rifle': 'plasma_rifle',
    'ec_caws': 'avenger',
    'napalm_strike': 'air_strike',
    'mine_strike': 'air_strike',
    'banana_strike': 'air_strike',
    'holy_strike': 'air_strike',
    'orbit_strike': 'air_strike',
    'skyfire': 'air_strike',
    'unfail_bazooka': 'bazooka',
    'unfail_grenade': 'grenade',
    'unfail_cluster_bomb': 'cluster_bomb',
    'banana_bomb': 'banana',
    'unfail_banana_bomb': 'banana',
    'super_banana_bomb': 'banana',
    'mega_banana_bomb': 'banana',
    'mini_banana': 'banana',
    'breaking_banana': 'banana',
    'unfail_uzi': 'uzi',
    'unfail_minigun': 'minigun',
    'unfail_mine': 'mine',
    'unfail_dynamite': 'dynamite',
    'unfail_old_woman': 'old_woman',
    'unfail_sheep': 'sheep',
    'fire_sheep': 'sheep',
    'poison_sheep': 'sheep',
    'unfail_laser_rifle': 'laser_rifle',
    'unfail_plasma_rifle': 'plasma_rifle',
    'unfail_gauss_rifle': 'gauss_rifle',
    'prod': 'baseball_bat',
    'firepunch': 'baseball_bat',
    'kamikaze': 'baseball_bat',
    'shocker': 'baseball_bat',
    'battle_axe': 'baseball_bat',
    'power_axe': 'baseball_bat',
    'power_bat': 'baseball_bat',
    'ec_panhammer': 'baseball_bat',
    'medikit': 'choose_worm',
    'super_medikit': 'choose_worm',
    'skip_go': 'choose_worm',
    'laser_sight': 'choose_worm',
    'low_gravity': 'choose_worm',
    'fast_walk': 'choose_worm',
    'ultra_scaner': 'choose_worm',
    'blow_torch': 'choose_worm',
    'pneumatic_drill': 'choose_worm',
    'parachute': 'choose_worm',
    'girder': 'choose_worm',
    'girder_pack': 'choose_worm',
    'jet_pack': 'choose_worm',
    'teleport': 'choose_worm',
    'upg_teleport': 'choose_worm',
    'upg_jet_pack': 'choose_worm',
    'ag_pack': 'choose_worm',
    'add_time': 'choose_worm',
    'upg_teleport2': 'choose_worm',
    'emg_teleport': 'choose_worm',
    'invisibility': 'choose_worm',
    'dynamite_bomblet': 'dynamite_bunch',
    'pulse_pistol': 'plasma_pistol',
    'luiston': 'plasma_pistol',
    'ultra_rifle': 'turbo_rifle',
    'void_melody': 'kenton_bazooka',
    'multip83': 'multip14'
};

// Map rez weapons to whatever
for (let i = 124; i <= 144; i++) {
    FALLBACK_MAP[`rez${i}`] = 'bazooka';
}

const preloadLines = [
    '// AUTO-GENERATED BY generate_preloads.cjs',
    'import { Scene } from "phaser";',
    '',
    'export const WEAPON_PROJ_FRAMES: Record<string, number> = {};',
    'export const WEAPON_HELD_FRAMES: Record<string, number> = {};',
    '',
    'export function preloadWeapons(scene: Scene) {'
];

const heldFramesMap = {};
const projFramesMap = {};

for (const key of keys) {
    let searchKey = key;
    if (searchKey.startsWith('unfail_')) searchKey = searchKey.replace('unfail_', '');
    if (searchKey.startsWith('super_')) searchKey = searchKey.replace('super_', '');
    if (searchKey.startsWith('upg_')) searchKey = searchKey.replace('upg_', '');
    if (searchKey === 'pistol') searchKey = 'handgun';
    if (searchKey === 'banana_bomb' || searchKey === 'mega_banana_bomb') searchKey = 'banana';
    if (searchKey.includes('dynamite_bunch')) searchKey = 'dynamite_bunch';

    if (FALLBACK_MAP[searchKey]) searchKey = FALLBACK_MAP[searchKey];
    if (FALLBACK_MAP[key]) searchKey = FALLBACK_MAP[key];

    let iconFile = null;
    if (files.includes(`${searchKey}_proj.png`)) {
        iconFile = `${searchKey}_proj.png`;
    } else if (files.includes(`${searchKey}_held_0.png`)) {
        iconFile = `${searchKey}_held_0.png`;
    } else if (files.includes(`${searchKey}_0.png`)) {
        iconFile = `${searchKey}_0.png`;
    } else if (files.includes(`${searchKey}.png`)) {
        iconFile = `${searchKey}.png`;
    } else {
        const matching = files.find(f => f.startsWith(searchKey + '_'));
        if (matching) iconFile = matching;
    }

    if (!iconFile) iconFile = 'bazooka_proj.png';

    preloadLines.push(`        scene.load.image('icon_${key}', '/weapons/${iconFile}');`);

    // Load held sprite if exists
    let heldFrameCount = 0;
    while (files.includes(`${searchKey}_held_${heldFrameCount}.png`)) {
        heldFrameCount++;
    }
    
    if (heldFrameCount > 0) {
        if (heldFrameCount === 1) {
            preloadLines.push(`        scene.load.image('held_${key}', '/weapons/${searchKey}_held_0.png');`);
        } else {
            // Load as multiple images and we'll create anims later if needed
            preloadLines.push(`        scene.load.image('held_${key}', '/weapons/${searchKey}_held_0.png');`);
            for (let i = 0; i < heldFrameCount; i++) {
                preloadLines.push(`        scene.load.image('held_${key}_${i}', '/weapons/${searchKey}_held_${i}.png');`);
            }
            heldFramesMap[key] = heldFrameCount;
        }
    } else {
        preloadLines.push(`        scene.load.image('held_${key}', '/weapons/${iconFile}');`); // Fallback held to icon
    }

    // Special mapping for projectiles of guns
    const GUN_BULLETS = {
        'pistol': 'bullet_standard',
        'beretta': 'bullet_standard',
        'handgun': 'bullet_standard',
        'peacemaker': 'bullet_standard',
        'shotgun': 'bullet_shotgun',
        'ec_caws': 'bullet_shotgun',
        'uzi': 'bullet_standard',
        'unfail_uzi': 'bullet_standard',
        'minigun': 'bullet_minigun',
        'unfail_minigun': 'bullet_minigun',
        'air_minigun': 'bullet_minigun',
        'laser_pistol': 'laser',
        'laser_pistol2': 'laser',
        'laser_rifle': 'laser',
        'unfail_laser_rifle': 'laser',
        'laser_at_rifle': 'laser',
        'laser_minigun': 'laser',
        'pulse_pistol': 'pulse',
        'luiston': 'pulse',
        'plasma_pistol': 'plasma',
        'plasma_rifle': 'plasma',
        'unfail_plasma_rifle': 'plasma',
        'plasma_at_rifle': 'plasma',
        'plasma_minigun': 'plasma',
        'gauss_pistol': 'gauss',
        'gauss_pistol2': 'gauss',
        'gauss_rifle': 'gauss',
        'unfail_gauss_rifle': 'gauss',
        'gauss_minigun': 'gauss',
        'hunting_rifle': 'bullet_standard',
        'sniper_rifle': 'bullet_standard',
        'bozar': 'bullet_standard',
        'rad_rifle': 'bullet_standard',
        'bozar16': 'bullet_standard',
        'bozar24s': 'bullet_standard',
        'avenger': 'bullet_standard'
    };

    let projSearchKey = searchKey;
    if (GUN_BULLETS[key]) {
        projSearchKey = GUN_BULLETS[key];
    }

    // Load projectile sprite if exists
    let projFrameCount = 0;
    while (files.includes(`${projSearchKey}_proj_${projFrameCount}.png`)) {
        projFrameCount++;
    }

    if (projFrameCount > 0) {
        if (projFrameCount === 1) {
            preloadLines.push(`        scene.load.image('proj_${key}', '/weapons/${projSearchKey}_proj_0.png');`);
        } else {
            preloadLines.push(`        scene.load.image('proj_${key}', '/weapons/${projSearchKey}_proj_0.png');`);
            for (let i = 0; i < projFrameCount; i++) {
                preloadLines.push(`        scene.load.image('proj_${key}_${i}', '/weapons/${projSearchKey}_proj_${i}.png');`);
            }
            projFramesMap[key] = projFrameCount;
        }
    } else if (files.includes(`${projSearchKey}_proj.png`)) {
        preloadLines.push(`        scene.load.image('proj_${key}', '/weapons/${projSearchKey}_proj.png');`);
    } else {
        preloadLines.push(`        scene.load.image('proj_${key}', '/weapons/${iconFile}');`); // Fallback proj to icon
    }
}

preloadLines.push(`}`);
preloadLines.push(``);
preloadLines.push(`Object.assign(WEAPON_PROJ_FRAMES, ${JSON.stringify(projFramesMap, null, 4)});`);
preloadLines.push(`Object.assign(WEAPON_HELD_FRAMES, ${JSON.stringify(heldFramesMap, null, 4)});`);

fs.writeFileSync('src/game/data/weapon_preloads.ts', preloadLines.join('\n'));
console.log('Done!');
